# Generated by Django 5.0.7 on 2024-10-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_winner_paid_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
