# Generated by Django 5.0.7 on 2024-11-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_winner_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
